<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    $vendorDir . '/joseph-lenton/php-error/src/php_error.php',
);
